SQL = {
    'hot_goods': '''
        CREATE TABLE IF NOT EXISTS `hot_goods_{0}` (
            `id` VARCHAR(100) NOT NULL COMMENT '商品id',
            `platform` VARCHAR(20) NOT NULL DEFAULT 'ebay' COMMENT '平台',
            `site` VARCHAR(255) DEFAULT NULL COMMENT '商品所属站点',
            `title` VARCHAR(255) NOT NULL COMMENT '商品信息',
            `default_image` VARCHAR(255) DEFAULT NULL COMMENT '主图',
            `other_images` TEXT COMMENT '商品其他图片，json格式',
            `price` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品售价',
            `currency` VARCHAR(255) DEFAULT NULL COMMENT '货币符号',
            `total_sold` INT(11) NOT NULL DEFAULT '0' COMMENT '总销量',
            `hit_count` INT(11) DEFAULT NULL COMMENT '访问量',
            `goods_category` VARCHAR(255) NOT NULL COMMENT '商品分类',
            `goods_url` VARCHAR(255) DEFAULT NULL COMMENT '商品页面访问地址',
            `shop_name` VARCHAR(255) DEFAULT NULL COMMENT '店铺名称',
            `shop_feedback_score` INT(11) DEFAULT NULL COMMENT '店铺评分',
            `shop_feedback_percentage` DOUBLE(10,2) DEFAULT NULL COMMENT '店铺好评率',
            `shop_open_time` TIMESTAMP NULL DEFAULT NULL COMMENT '店铺开张时间',
            `publish_time` TIMESTAMP NULL DEFAULT NULL COMMENT '上架时间',
            `weeks_sold` INT(11) NOT NULL DEFAULT '0' COMMENT '周销量',
            `weeks_sold_money` DOUBLE(20,2) DEFAULT '0.00' NOT NULL COMMENT '近7天销售金额',
            `day_sold` INT(11) NOT NULL DEFAULT '0' COMMENT '当日销量',
            `last_weeks_sold` INT(11) DEFAULT NULL COMMENT '上上周销量',
            `trade_increase_rate` DOUBLE(10,4) DEFAULT NULL COMMENT '交易增幅比率，比如：0.1256 表示12.56%',
            `record` TEXT COMMENT '商品 14 天相关统计数据记录',
            `variations` TEXT COMMENT '商品多属性数据',
            `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
            PRIMARY KEY (`id`),
            KEY `idx_title` (`title`(250)) COMMENT '商品标题',
            KEY `idx_goods_category` (`goods_category`(250)),
            KEY `idx_shop_name` (`shop_name`(250)),
            KEY `idx_price` (`price`) USING BTREE COMMENT '售价',
            KEY `idx_weeks_sold` (`weeks_sold`) COMMENT '商品周销量',
            KEY `idx_trade_increase_rate` (`trade_increase_rate`) COMMENT '交易增幅',
            KEY `idx_shop_open_time` (`shop_open_time`),
            KEY `idx_total_sold` (`total_sold`) USING BTREE COMMENT '总销量'
        ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COMMENT='热销商品表';''',
    'new_goods': '''
        CREATE TABLE IF NOT EXISTS `new_goods_{0}` (
            `id` VARCHAR(100) NOT NULL COMMENT '商品id',
            `platform` VARCHAR(20) NOT NULL DEFAULT 'ebay' COMMENT '平台',
            `site` VARCHAR(255) DEFAULT NULL COMMENT '商品所属站点',
            `title` VARCHAR(255) NOT NULL COMMENT '商品信息',
            `default_image` VARCHAR(255) DEFAULT NULL COMMENT '主图',
            `other_images` TEXT COMMENT '商品其他图片，json格式',
            `price` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品售价',
            `currency` VARCHAR(255) DEFAULT NULL COMMENT '货币符号',
            `total_sold` INT(11) NOT NULL DEFAULT '0' COMMENT '总销量',
            `hit_count` INT(11) DEFAULT NULL COMMENT '访问量',
            `goods_category` VARCHAR(255) NOT NULL COMMENT '商品分类',
            `goods_url` VARCHAR(255) DEFAULT NULL COMMENT '商品页面访问地址',
            `shop_name` VARCHAR(255) DEFAULT NULL COMMENT '店铺名称',
            `shop_feedback_score` INT(11) DEFAULT NULL COMMENT '店铺评分',
            `shop_feedback_percentage` DOUBLE(10,2) DEFAULT NULL COMMENT '店铺好评率',
            `shop_open_time` TIMESTAMP NULL DEFAULT NULL COMMENT '店铺开张时间',
            `publish_time` TIMESTAMP NULL DEFAULT NULL COMMENT '上架时间',
            `weeks_sold` INT(11) NOT NULL DEFAULT '0' COMMENT '周销量',
            `weeks_sold_money` DOUBLE(20,2) DEFAULT '0.00' NOT NULL COMMENT '近7天销售金额',
            `day_sold` INT(11) NOT NULL DEFAULT '0' COMMENT '当日销量',
            `last_weeks_sold` INT(11) DEFAULT NULL COMMENT '上上周销量',
            `trade_increase_rate` DOUBLE(10,4) DEFAULT NULL COMMENT '交易增幅比率，比如：0.1256 表示12.56%',
            `record` TEXT COMMENT '商品 14 天相关统计数据记录',
            `variations` TEXT COMMENT '商品多属性数据',
            `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
            PRIMARY KEY (`id`),
            KEY `idx_title` (`title`(250)) COMMENT '商品标题',
            KEY `idx_goods_category` (`goods_category`(250)),
            KEY `idx_shop_name` (`shop_name`(250)),
            KEY `idx_price` (`price`) USING BTREE COMMENT '售价',
            KEY `idx_weeks_sold` (`weeks_sold`) COMMENT '商品周销量',
            KEY `idx_trade_increase_rate` (`trade_increase_rate`) COMMENT '交易增幅',
            KEY `idx_shop_open_time` (`shop_open_time`),
            KEY `idx_total_sold` (`total_sold`) USING BTREE COMMENT '总销量'
        ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COMMENT='热销商品表';''',
    'goods': '''
        CREATE TABLE IF NOT EXISTS `goods_{0}` (
            `id` VARCHAR(100) NOT NULL COMMENT '商品id',
            `platform` VARCHAR(20) NOT NULL DEFAULT 'ebay' COMMENT '平台',
            `site` VARCHAR(255) DEFAULT NULL COMMENT '商品所属站点',
            `title` VARCHAR(255) NOT NULL COMMENT '商品信息',
            `default_image` VARCHAR(255) DEFAULT NULL COMMENT '主图',
            `other_images` TEXT COMMENT '商品其他图片，json格式',
            `price` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '商品售价',
            `currency` VARCHAR(255) DEFAULT NULL COMMENT '货币符号',
            `total_sold` INT(11) NOT NULL DEFAULT '0' COMMENT '总销量',
            `hit_count` INT(11) DEFAULT NULL COMMENT '访问量',
            `goods_category` VARCHAR(255) NOT NULL COMMENT '商品分类',
            `goods_url` VARCHAR(255) DEFAULT NULL COMMENT '商品页面访问地址',
            `shop_name` VARCHAR(255) DEFAULT NULL COMMENT '店铺名称',
            `shop_feedback_score` INT(11) DEFAULT NULL COMMENT '店铺评分',
            `shop_feedback_percentage` DOUBLE(10,2) DEFAULT NULL COMMENT '店铺好评率',
            `shop_open_time` TIMESTAMP NULL DEFAULT NULL COMMENT '店铺开张时间',
            `publish_time` TIMESTAMP NULL DEFAULT NULL COMMENT '上架时间',
            `weeks_sold` INT(11) NOT NULL DEFAULT '0' COMMENT '周销量',
            `weeks_sold_money` DOUBLE(20,2) DEFAULT '0.00' NOT NULL COMMENT '近7天销售金额',
            `day_sold` INT(11) NOT NULL DEFAULT '0' COMMENT '当日销量',
            `last_weeks_sold` INT(11) DEFAULT NULL COMMENT '上上周销量',
            `trade_increase_rate` DOUBLE(10,4) DEFAULT NULL COMMENT '交易增幅比率，比如：0.1256 表示12.56%',
            `is_hot` ENUM('0','1') DEFAULT '0' COMMENT '是否爆款，0-否，1-是',
            `is_new` ENUM('0','1') DEFAULT '0' COMMENT '是否新品，0-否，1-是',
            `record` TEXT COMMENT '商品 14 天相关统计数据记录',
            `variations` TEXT COMMENT '商品多属性数据',
            `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
            PRIMARY KEY (`id`),
            KEY `idx_title` (`title`(250)) COMMENT '商品标题',
            KEY `idx_goods_category` (`goods_category`(250)),
            KEY `idx_shop_name` (`shop_name`(250)),
            KEY `idx_price` (`price`) USING BTREE COMMENT '售价',
            KEY `idx_weeks_sold` (`weeks_sold`) COMMENT '商品周销量',
            KEY `idx_trade_increase_rate` (`trade_increase_rate`) COMMENT '交易增幅',
            KEY `idx_shop_open_time` (`shop_open_time`),
            KEY `idx_total_sold` (`total_sold`) USING BTREE COMMENT '总销量'
        ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COMMENT='商品表';''',
    'shop_statistics': '''
        CREATE TABLE IF NOT EXISTS `shop_statistics_{0}` (
          `id` int(100) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
          `platform` varchar(20) NOT NULL DEFAULT 'ebay' COMMENT '平台',
          `shop_name` varchar(255) DEFAULT NULL COMMENT '店铺名称',
          `shop_feedback_score` int(11) DEFAULT NULL COMMENT '店铺评分',
          `shop_feedback_percentage` double(10,2) DEFAULT NULL COMMENT '店铺好评率',
          `sold_goods_count` int(11) DEFAULT NULL COMMENT '店铺里有销量的商品数',
          `total_goods_count` int(11) DEFAULT NULL COMMENT '店铺商品总数',
          `total_sold` int(11) DEFAULT NULL COMMENT '店铺日销量',
          `weeks_sold` int(11) DEFAULT NULL COMMENT '近7天店铺销量',
          `last_weeks_sold` int(11) DEFAULT NULL COMMENT '上一周店铺销量',
          `weeks_inc_ratio` double(10,4) DEFAULT NULL COMMENT '周增幅，如：0.1223代表12.23%',
          `amount` double(20,2) DEFAULT NULL COMMENT '近7天销售金额',
          `shop_open_time` timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '店铺开张时间',
          `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '添加时间',
          `updated_at` timestamp NULL DEFAULT NULL COMMENT '更新时间',
          PRIMARY KEY (`id`),
          UNIQUE KEY `idx_shop_name` (`platform`,`shop_name`),
          KEY `idx_weeks_inc_ratio` (`weeks_inc_ratio`)
        ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='店铺统计表';''',
}
